name: Release (Production)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - run: terraform -chdir=./supabase/remotes/ init -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" -backend-config='endpoints={s3="${{ secrets.TERRAFORM_BACKEND_ENDPOINT }}"}' -backend-config="access_key=${{ secrets.TERRAFORM_BACKEND_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.TERRAFORM_BACKEND_SECRET_KEY }}"
      - run: terraform -chdir=./supabase/remotes/ apply -auto-approve -no-color -var="supabase_access_token=${{ secrets.SUPABASE_ACCESS_TOKEN }}" -var="org_id=${{ secrets.SUPABASE_ORG_ID }}" -var="db_password=${{ secrets.SUPABASE_DB_PASSWORD }}" -var="project_name=${{ secrets.SUPABASE_PROJECT_NAME }}"

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref "$(terraform -chdir=./supabase/remotes/ output -raw supabase_project_id)"
      - run: supabase db push
